"""empty message

Revision ID: 72ff13cdd795
Revises: a06508d952d4
Create Date: 2024-09-16 15:16:38.993603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ff13cdd795'
down_revision = 'a06508d952d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earthquakes', sa.Column('magnitude', sa.Float(), nullable=True))
    op.drop_column('earthquakes', 'magnintude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earthquakes', sa.Column('magnintude', sa.FLOAT(), nullable=True))
    op.drop_column('earthquakes', 'magnitude')
    # ### end Alembic commands ###
